Link dos proximos capitulos
meleu/bashscripting pull request #4
Opened 2020-01-19 17:07 UTC by redmanndotsh

Saudações, @meleu!
Muito bacana o seu projeto. Obrigado por compartilhá-lo com a comunidade e apoiar o software livre. Eu amo Shell e amo ler Aurélio!
Pra mim, seria uma honra se você aceitasse este PR. Basicamente, o que eu fiz foi referenciar os capítulos, desta forma: ![image](https://user-images.githubusercontent.com/24627793/72684988-337c3300-3ac4-11ea-911f-401a65ed64d5.png)

Porém, só agora reparei em algumas inconsistências, como por exemplo: todos os links estarem apontando para o meu fork. Se você aceitar esse pull, me comprometo em arrumar essa bagunça.

Um abraço, e obrigado!

2020-01-19 18:59 UTC, meleu commented
yo!
Fico lisonjeado ao perceber que ainda há interesse por esse documento.
Me faz perceber que eu preciso dar uma atualizada nele, pois depois desses quase 20 anos já aprendi um monte de coisa nova e melhores práticas de codificação.

Sobre o PR, antes de dar um merge eu gostaria que você colocasse as URLs relativas ao invés de absolutas.

Exemplo:
```
**Capítulo 02: [Variáveis e Parâmetros →](/chapter-02)**
```

Pode ser?

A propósito: recentemente comecei um novo projeto para compartilhar meu conhecimento sobre shell script, dá uma olhada lá que tou publicando um conteúdo mais "moderninho": https://meleu.sh/

2020-01-19 19:00 UTC, meleu requested changes
Substituir URLs absolutas por relativas.

2020-01-20 02:18 UTC, redmanndotsh commented
> yo!
> Fico lisonjeado ao perceber que ainda há interesse por esse documento.
> Me faz perceber que eu preciso dar uma atualizada nele, pois depois desses quase 20 anos já aprendi um monte de coisa nova e melhores práticas de codificação.
> 
> Sobre o PR, antes de dar um merge eu gostaria que você colocasse as URLs relativas ao invés de absolutas.
> 
> Exemplo:
> 
> ```
> **Capítulo 02: [Variáveis e Parâmetros →](/chapter-02)**
> ```
> 
> Pode ser?
> 
> A propósito: recentemente comecei um novo projeto para compartilhar meu conhecimento sobre shell script, dá uma olhada lá que tou publicando um conteúdo mais "moderninho": https://meleu.sh/

Acho que aprender Shell foi umas das coisas mais legais que eu fiz. Mesmo as coisas simples, como abrir o browser pelo terminal, me ajudam muito.

Quanto aos links relativos, eu não havia pensado nisso. É genial! Deixe comigo.

Sobre o seu blog, eu já andei dcando uns cliques neles. Aliás, a UI dele tá ótima! Você que fez?

Até a revisão, meleu.
Um abraço!

2020-01-21 20:22 UTC, redmanndotsh commented
**Correções aplicadas.**

2020-01-22 03:43 UTC, merged